/* config.js — generated by the build. Public settings only: the Supabase anon key is designed to be public. */
window.APP_CONFIG = {
  "slug": "phishing-email-analyzer",
  "name": "Phish Scope",
  "supabaseUrl": "",
  "supabaseAnonKey": "",
  "aiProxy": "",
  "google": false,
  "prompts": [
    {
      "say": "Is this one safe to click?",
      "does": "Scans the pasted email and explains the verdict."
    },
    {
      "say": "Always trust mail from my bank, example-bank.com",
      "does": "Adds the domain to your trusted list."
    },
    {
      "say": "Give me a harder practice email",
      "does": "Opens the training game with a new message."
    }
  ]
};
